import React, {Component, useState} from 'react';
import {
  View,
  Text,
  StyleSheet,
  Image,
  ImageBackground,
  Pressable,
  TouchableOpacity,
  StatusBar,
  TextInput,
} from 'react-native';
import {ScrollView} from 'react-native-gesture-handler';
import HeaderComp from '../../Components/HeaderComp';
import {ProfileListComp} from '../../Components/ProfileListComp';
import WrapperContainer from '../../Components/WrapperContainer';
import imagePath from '../../constants/imagePath';
import strings from '../../constants/lang';
import colors from '../../styles/colors';
import {moderateScale} from '../../styles/responsiveSize';
import styles from './styles';
import QRCode from 'react-native-qrcode-svg';
import ButtonComp from '../../Components/ButtonComp';
import navigationStrings from '../../constants/navigationStrings';
import VerifyEmail from '../../Components/VerifyEmail';

const EditProfile = ({navigation}) => {
  const goBack = () => {
    navigation.goBack();
};

const [activee , setactivee] = useState(false);
const toggleModal = ()=>{
    setactivee(!activee)
}
  return (
    <WrapperContainer>
      <View style={styles.container}>

          <HeaderComp text={strings.Editprofile}
          onBackPress={goBack}/>
        
       <TouchableOpacity>
           <View style={styles.changepic}>
               <Image style={styles.profilepic} source={imagePath.profile3}/>
               <View style={styles.textView}>
               <Text style={styles.Changeprofilepicture}>{strings.Changeprofilepicture}</Text>
               <Image source={imagePath.ic_gray_arrow}/>
               </View>
           </View>
       </TouchableOpacity>
        
        <View style={styles.bgView}>
            <Text style={styles.ProfileName}>{strings.ProfileName}</Text>
        </View>
        <View style={styles.bgView}>
            <Text style={styles.ProfileName}>{strings.vipayid}</Text>
        </View>
        <Text style={styles.vipayidtxt}>{strings.ViPayIDisautogenerated}</Text>
        <View style={styles.bgView}>
            <TextInput style={styles.ProfileEmail}>{strings.ProfileEmail}</TextInput>
        </View>
        <View style={styles.phoneView}>
            <Text style={styles.countrycode}>{strings.countrycode}</Text>
            <Text style={styles.line}/>
            <Text style={styles.Number}>{strings.Number}</Text>
        </View>
        <VerifyEmail showModal={activee} renderModal={toggleModal} />
        <View style={styles.btn}>
            <ButtonComp btnText={strings.Update} onPress={toggleModal}
            />
        </View>
      </View>
    </WrapperContainer>
  );
};
export default EditProfile;
